### ISSUE TITLE
Can complain about ambiguity where there is none

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-pg#10]
```
maciek@mothra:~$ heroku pg:psql bronze --app shogun-cedar
 !    Ambiguous identifier; multiple matching attachments found: HEROKU_POSTGRESQL_BRONZE, HEROKU_REDIS_BRONZE.
```

Clearly I'm not trying to `psql` into my Redis =)

**Comment by jdx** [comment]
@ransombriggs any ideas on how we could fix this? This is the old ruby code, but even if I ported it to node and apiv3 we would have the same problem since at the time I request the attachments I don't have a way to request just postgres attachments.

**Comment by ransombriggs** [comment]
@uhoh-itsmaciek @dickeyxxx yeah, this is something that would require an API change.  @geemus do you know of any endpoints offhand that allow scoping using a header or query params that we could emulate?  Pretty sure this is requesting something like `/addon-attachments/:attachment` and it would be nice if we could add a type to it so it only considers postgres.

**Comment by geemus** [comment]
Probably the closest would be the filter apps endpoint (which filters apps to just a specified list of ids): https://github.com/heroku/api/blob/master/lib/api/endpoints/api_v3/filters_apps.rb

**Comment by mathias** [comment]
@ransombriggs This is where having an `addon_service` filter on attachments resolver endpoint would be good. I'm not sure that it makes sense on the add-on resolver though.
