### ISSUE TITLE
pg:ps fails with 'column "waiting" does not exist'

### ISSUE THREAD

**Issue by spollack** [heroku/heroku-pg#114]
i'm running this command against heroku postgres 9.6.x databases. i'm running from OSX, heroku CLI installed via brew. 
```
heroku pg:ps --app rivaliq-usertest
ERROR:  column "waiting" does not exist
LINE 7:  waiting,
         ^
Timing is on.
Expanded display is used automatically.
Null display is "(null)".
Time: 73.484 ms
```

```
heroku --version
heroku-cli/6.6.13-57fc242 (darwin-x64) node-v7.9.0

which heroku
/usr/local/bin/heroku

ls -l /usr/local/bin/heroku
lrwxr-xr-x  1 spollack  admin  33 May 18 13:17 /usr/local/bin/heroku -> ../Cellar/heroku/6.6.7/bin/heroku

cat /usr/local/Cellar/heroku/6.6.7/libexec/node_modules/heroku-pg/package.json | grep "version"
  "version": "2.0.26",
```

I see there was a fix here in heroku-pg to be compatible with pg 9.6.x, but it doesn't seem to be working for me. 

Thanks,
Seth

**Comment by msakrejda** [comment]
Hi, thanks for reporting this. I've submitted a patch to triage this issue and we should be able to ship that shortly. In the meantime, I suspect you may be able to work around this by temporarily disabling your `.psqlrc` file. I apologize for the inconvenience.

**Comment by spollack** [comment]
thank you for the super-rapid response!
