### ISSUE TITLE
pg:backups:restore should require an explicit database

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-pg#127]
Right now it defaults to DATABASE_URL, but there's little reason to do that and it's a bit of a foot gun. We should require the database to be explicitly specified.

**Comment by msakrejda** [comment]
So this is tricky because right now the backup is the first argument and is also optional. While we could make the command "smart" and try to figure out if the argument (if only one is provided) is a database name or a backup name, I think this may not always be unambiguous, and is always kinda weird.

We could make the backup argument required, too, or we could reverse the order of the arguments (although this breaks consistency with most other `pg:*` commands which take the database as the last, usually optional argument). Maybe we can do something else, but I can't think of other reasonable options off the top of my head.

Thoughts @heroku/department-of-data?

See also https://trello.com/c/dn5xem1V/184-change-default-pgrestore-behavior

**Comment by camillebaldock** [comment]
I'd vote in favour of `While we could make the command "smart" and try to figure out if the argument (if only one is provided) is a database name or a backup name, I think this may not always be unambiguous, and is always kinda weird.`.

Making URL detection smarter is needed in the context of the credentials project anyway (see https://trello.com/c/seYyXv95/1971-creds-unhelpful-suggestions-for-database-urls-on-most-pg-commands-when-the-database-has-credential-attachments-cannot-use-other-) and I believe combined with a confirmation text that specifies again which `DATABASE_URL` has been selected by default, this could be a altogether good user experience.

I'd like to suggest I take a stab at that once I've got a patch for https://trello.com/c/seYyXv95/1971-creds-unhelpful-suggestions-for-database-urls-on-most-pg-commands-when-the-database-has-credential-attachments-cannot-use-other-: thoughts?

**Comment by msakrejda** [comment]
URL detection?

**Comment by camillebaldock** [comment]
@uhoh-itsmaciek by `URL detection` above I mean: creating a method in the CLI that takes a string like "DATABASE_URL" to knowing whether it is a valid attachment. This needs to look at a list of attachments and excludes ones with a namespace. Apologies for confusing explanation above.

**Comment by msakrejda** [comment]
Ah, I see, thanks. The v6 custom flags stuff should simplify this, no? Although I suppose we can't use that if we want this behavior.

We also need to consider how this fits in with our other CLI conventions. Any thoughts on this @dickeyxxx or @heroku/cli? Basically, we want to make the *second* argument to the command no longer optional, but that introduces some weirdness, because we want to keep the first argument optional. We could switch the order of the arguments, but that makes it inconsistent with most other data commands, where we've tried to keep the data store as the last argument.

**Comment by jdx** [comment]
there is some precedent for doing things with either a flag or an arg like `heroku destroy` that can be `heroku destroy foo` or `heroku destroy -a foo`: https://github.com/heroku/heroku-apps/blob/master/commands/apps/destroy.js#L10

When I first put that in I was unsure if it was a great idea, but my philosophy is to do what the user wants if you know what they mean, and this is one of those cases for heroku destroy. It's been like that for a couple years probably and I don't think it's caused any grief.

It's not totally the same thing though. There are other places in the code (though I can't seem to find it now) where we essentially do `context.args.pop()` to have an optional first argument.

I feel like the database might be better as a flag. Often we've found that args work well when there is just one, but having 2 makes it so you have to look at the docs every time you want to do something. It's worth the extra character to type in the flag. This would also let you use the new flag stuff to abstract the logic for the database down, possibly making it configurable to either use DATABASE_URL or not, or required or not.

Changing it in this one place though would be weird, ideally that would happen everywhere and that's a big change both for us and for the users.

These are my thoughts, I'm not really sure which is the right way to go though. I think if it were me I'd try to write up something to make it work like today but do what you said above. I think it would look something like this:

```js
let [backup, database] = context.args
if (!database) {
  database = backup
  backup = null
}
```

**Comment by neovintage** [comment]
we have to be very careful about changing behavior. 

- What problems are customers going to run into?
- Is there a way to see how many customers are running the command without specifying the attachment / resource?

**Comment by msakrejda** [comment]
We've decided that fixing this only introduces the potential for other, equally tricky problems. See linked Trello card.
