### ISSUE TITLE
Raises `Parameter "url" must be a string, not undefined` when the default db (`DATABASE_URL`) is an attached addon

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg#15]
```
$ heroku pg:locks -a keiko-sushi
 ▸    Parameter "url" must be a string, not undefined
```

```
$ heroku addons -a keiko-sushi
...
 heroku-postgresql (postgresql-convex-3794)           hobby-basic  (billed to keiko-cedar10 app)
 ├─ as DATABASE
 ├─ as HEROKU_POSTGRESQL_ONYX
 ├─ as MAIN_DB
 └─ as HEROKU_POSTGRESQL_BLACK on keiko-cedar10 app
```

This is coming from [here](https://github.com/heroku/heroku-pg/blob/master/lib/fetcher.js#L25), because `config[addon.config_vars[0]]` is `undefined`. It's undefined because `addon.config_vars[0]` is `HEROKU_POSTGRESQL_BLACK_URL`, which I don't have it in keiko-sushi app (I only have it with keiko-cedar10 app). `addon.config_vars` is being `HEROKU_POSTGRESQL_BLACK_URL` because that's what owning-app has.

Likely need to change [this part](https://github.com/heroku/heroku-pg/blob/master/lib/fetcher.js#L21)?

**Comment by jdx** [comment]
this is fixed right? cc @ransombriggs

**Comment by keiko713** [comment]
at least I can't repro anymore, cool cool

```
$ heroku pg:locks -a keiko-sushi
 pid | relname | transactionid | granted | query_snippet | age 
-----+---------+---------------+---------+---------------+-----
(0 rows)
```

**Comment by jdx** [comment]
we put a lot of changes in around how we fetch config vars

**Comment by ransombriggs** [comment]
@dickeyxxx yeah, this was one of the things that I fixed where we now use the attachment `config_vars` instead of the addon `config_vars`
