### ISSUE TITLE
`Couldn't find that add-on.` when there is no default database configured in DATABASE_URL

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg#16]
Expected behavior (and is working well with `heroku pg:diagnose`, because it's still using Ruby one... I think?):

```
$ heroku pg:diagnose -a keiko-cedar10
 !    No default database configured in DATABASE_URL. Valid alternatives are: HEROKU_POSTGRESQL_BLACK_URL
```

Confusing behavior with commands of heroku-pg-extras:

```
$ heroku pg:locks -a keiko-cedar10
 ▸    Couldn't find that add-on.
```

Likely it's failing [here](https://github.com/heroku/heroku-pg/blob/master/lib/fetcher.js#L12), where it tries to search the addon `DATABASE_URL` with heroku-cli-addons and it does say it couldn't find that add-on.
I guess this part of error handling is not imported to heroku-pg? https://github.com/heroku/heroku/blob/master/lib/heroku/helpers/heroku_postgresql.rb#L223-L229

**Comment by pdfrod** [comment]
A had a typo on the app's name and also got the very confusing error message: `Couldn't find that add-on.`

**Comment by keiko713** [comment]
I'm seeing confused customers time to time (pretty regularly), would be nice to see some improvement.

**Comment by msakrejda** [comment]
Yeah, this is now using [resolve](https://github.com/heroku/heroku-pg/blob/master/lib/fetcher.js#L8) from `heroku-cli-addons`--that doesn't handle some situations as gracefully. I know @dickeyxxx had it on his radar to improve this.

**Comment by jdx** [comment]
This is turning out to be a seriously hard problem, but @mathias is going to spend some time on it while I'm gone.

I realize that might seem surprising to just change the error message here, but we have a lot of inconsistency with how we reference add-ons and we want to come up with what should be the right way to do it.

Having said that, if it drags on too long, we do plan to ship a quicker fix to at least get these errors back to how they were before, but it's a little tricker with apiv3 than it was with the old API.

Also, we shouldn't ship any new pg commands until we resolve this ticket.

**Comment by msakrejda** [comment]
@mathias feel free to ping me if you want details on how Shogun interacts with this (not that it does all that much) or just need a rubber duck.

**Comment by mathias** [comment]
@uhoh-itsmaciek Howdy. My understanding is that this is simply going to make the serverside solution for resolution the same between `addons` and `pg` commands, and generate better error messages -- we're not improving the range of things that can be resolved from what it is now. 

Can you elaborate on 

> using resolve from heroku-cli-addons--that doesn't handle some situations as gracefully. 

?

Thanks.

**Comment by msakrejda** [comment]
Is it different now? `heroku-pg` just calls this function:

``` javascript
function * addon (app, db) {
  const {resolve} = require('heroku-cli-addons')

  let attachment = yield resolve.attachment(cli.heroku, app, db)
  return attachment.addon
}
```

Is what addons does different?

Re: not handling things gracefully: see e.g., #10 and #17--that wasn't an issue with the old client-side resolution mechanism used in Ruby.

**Comment by ransombriggs** [comment]
This endpoint is not used yet by the CLI, leaving open until verified fixed

**Comment by mathias** [comment]
@ransombriggs :+1: sorry for marking it wrong.
