### ISSUE TITLE
heroku pg:psql throws the error psql:could not translate host name "ec2.<>.amazonaws.com"  to address: Unknown server error. 

### ISSUE THREAD

**Issue by Srigowri** [heroku/heroku-pg#169]
I am trying to use the heroku postgres database. I have installed PostgresSQL 10 on my windows system. psql command works fine while connecting to the local database. While connecting to heroku postgres,it throws the error saying could not translate host name. This maybe because of the proxy settings. 

Commands I have used are
**1.psql --host <hostname> --port 5432 --username <username> --dbname <dbname>
2.psql "dbname=<dbname> host=<hostname> user=<username> password=<password> port=5432"
3.heroku pg:psql postgresql-<>-<> --app <appname>**

All these commands give the same error Unknown server error.
Is there a way around this or any alternative? 
Thanks in advance!

**Comment by msakrejda** [comment]
Can you please file a support ticket at https://help.heroku.com ? This sounds like an issue with your configuration and not heroku-pg.
