### ISSUE TITLE
CLI updates for new PG plans

### ISSUE THREAD

**Issue by quirkey** [heroku/heroku-pg#176]
We're supporting core in allowing users to update to the brand new pg plans.

There's a hard launch date here of Jan 17th.

https://xray.herokai.com/projects/new-postgres-plans-eligible-databases
https://salesforce.quip.com/T9iqAwdCLCsZ

**Comment by msakrejda** [comment]
This *should* be just waiting for @heroku/dod-core to change the pg:info endpoint output, but let's keep this issue open to track that and validate it.

/cc @genslein

**Comment by msakrejda** [comment]
This was done server-side.
