### ISSUE TITLE
[Feature request] Support -f for the pg:psql command

### ISSUE THREAD

**Issue by stof** [heroku/heroku-pg#201]
The `-f` option of `psql` allowing to run a sql file in psql is quite handy when having to write a big query, instead of copy-pasting it in an interactive session. But `heroku pg:psql` does not support it (while it supports `-c`).

My workaround until now was to retrieve the credentials URL and then use `psql` directly. However, this does not work for a private plan DB, as this would not go through the bastion SSH tunnel (and yes, I just went reading the source code of this package to understand how `pg:psql` could connect to the private DB).
It would be great if `-f` could be supported by `heroku pg:psql` directly.

**Comment by msakrejda** [comment]
@stof I think that sounds reasonable. As a workaround, you should be able to feed stdin to `pg:psql`:

```console
msakrejda@localhost:~$ echo 'select 1; select 2; select 3' > some.sql
msakrejda@localhost:~$ h pg:psql -a transferatu-maciek <some.sql
--> Connecting to postgresql-polished-66551
 ?column? 
----------
        1
(1 row)

 ?column? 
----------
        2
(1 row)

 ?column? 
----------
        3
(1 row)
```

**Comment by stof** [comment]
hmm, the workaround is nice. Thanks.

Supporting `-f` would still help. In case of an error somewhere in the file, the error message reports the line number in case of `-f`, while it does not when using stdin

**Comment by msakrejda** [comment]
Yep, I agree. To be frank, we don't have time to work on this in the near future, but I hope to get around to it at some point (or I would happily accept a patch, though note that our DevCenter documentation for writing plugins may now be referring to newer versions of our CLI framework that is not compatible with the version in use in heroku-pg).
