### ISSUE TITLE
Poor error handling with no databases

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-pg#58]
Via @cyberdelia 

```
maciek@mothra:~/code/aux/oki$ h pg:psql -a oki
 ▸    Unknown database: undefined. Valid options are:
maciek@mothra:~/code/aux/oki$ h addons -a oki
No add-ons for app oki.
```

Oki does have a DATABASE_URL, but it's a copy-and-paste from oki-cedar (and if we're doing this, others certainly also are). Ideally, we should either

 * fall back to DATABASE_URL if there are no add-ons or attachments
 * give a sensible error when there are no add-ons or attachments

**Comment by ransombriggs** [comment]
@uhoh-itsmaciek I went with the sensible error because it matches what the ruby code does.  The fix can be found here if you could review it quick https://github.com/heroku/heroku-pg/pull/59

**Comment by jdx** [comment]
this is 2 different issues right?

**Comment by msakrejda** [comment]
Well, the one issue was the poor error handling. I proposed an easy fix (what Ransom implemented in #59) and a more thorough but more complicated fix. We can add the more complicated fix as an enhancement down the line, but it's fine to keep this closed as the original issue is resolved.

**Comment by jdx** [comment]
Isn't it just really old apps that would have DATABASE_URL set to something non-pg? Since the API won't allow you to set that config var anymore I don't think.

**Comment by msakrejda** [comment]
```
maciek@mothra:~$ h create
Creating app... done, ⬢ nameless-bayou-78974
https://nameless-bayou-78974.herokuapp.com/ | https://git.heroku.com/nameless-bayou-78974.git
maciek@mothra:~$ h config:set DATABASE_URL=$(h config:get DATABASE_URL --app shogun-maciek) -a nameless-bayou-78974
Setting DATABASE_URL and restarting ⬢ nameless-bayou-78974... done, v4
DATABASE_URL: postgres://...
```

 ¯\\\_(ツ)\_/¯

**Comment by ransombriggs** [comment]
@dickeyxxx it only prevents you overwriting it if you have an addon that is setting it, since Macieks app does not have a database yet, it does not prevent it.  Here is the behavior for an app with an existing databse.
```
-> % heroku config:set DATABASE_URL=foobar -a rbriggs-sushi
Setting DATABASE_URL and restarting ⬢ rbriggs-sushi... !
 ▸    Cannot overwrite attachment values DATABASE_URL.
```

**Comment by jdx** [comment]
ahh ok
