### ISSUE TITLE
pg:diagnose is receiving the wrong format for plan name

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg#65]
pgdiagnose is expecting to receive the plan name like `standard-0`, instead of `heroku-postgresql:standard-0`.
This is causing the issue that we don't know the proper plan in pgdiagnose side, and always reporting RED for "Connection Count". The easy fix would be changing heroku-pg and pass the param that pgdiagnose expects.

https://github.com/heroku/pgdiagnose/blob/master/plans.go
https://github.com/heroku/heroku-pg/blob/master/test/commands/diagnose.js#L11

Perviously:

https://github.com/heroku/heroku/blob/master/lib/heroku/helpers/pg_diagnose.rb#L50

**Comment by jdx** [comment]
nice debugging!
