### ISSUE TITLE
pg:backups public-url is not BC

### ISSUE THREAD

**Issue by stof** [heroku/heroku-pg#67]
The old Ruby implementation had a ``-q`` option, which does not work anymore after the update switching to this repo command, breaking my script.

As the new command seems to have the behavior of the old quiet mode (i.e. outputting only the URL), I can update easily, but it would be a good idea to support the option in the BC layer.

**Comment by ransombriggs** [comment]
@stof thanks for filing this issue, I shipped a new version (5.5.10) you can get by running `heroku update` in case someone else runs into this issue.

**Comment by msakrejda** [comment]
Closing this as presumed fixed; please reopen if you still have issues.

**Comment by stof** [comment]
indeed, it is fixed
