### ISSUE TITLE
pg:pull does not tunnel through bastions

### ISSUE THREAD

**Issue by ahamidi** [heroku/heroku-pg#73]
The `pg:pull` command does not tunnel through bastions when used on a Private database. It instead tries to connect directly to the database instance.

**Comment by ransombriggs** [comment]
@ahamidi I was able to replicate this issue and hope to have a fix tomorrow.

**Comment by ransombriggs** [comment]
@ahamidi if you need an immediate fix, you can follow the steps outlined here to do a backup + restore https://devcenter.heroku.com/articles/heroku-postgres-import-export

**Comment by ransombriggs** [comment]
@ahamidi this is fixed in `5.6.2`, could you please `heroku update` and try again?

**Comment by ahamidi** [comment]
@ransombriggs Yep, works now. Thanks!
