### ISSUE TITLE
Does not cleanly handle Ctrl+C on long-running queries

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-pg#83]
It looks like this kills psql (instead of interrupting the query) and leaves the command shell in a bad state. I can't reproduce this on Ubuntu but @fnando reproduced this in OS X. It's not clear whether Windows is affected.

**Comment by jdx** [comment]
so `psql` is exiting but the command is still running?

**Comment by msakrejda** [comment]
That's a good question--I'll follow up.

**Comment by msakrejda** [comment]
Reinstalling (as per our conversation) worked for the affected user. @fnando, can you try reinstalling (upgrade won't help) the CLI and see if that fixes it for you, too? This may just be a fluke due to the bad signal handling in the one release.

**Comment by fnando** [comment]
It works. 👍

**Comment by msakrejda** [comment]
Ok, cool, thanks. I'll close this and we can revisit if we see it again and reinstalling doesn't fix it.
