### ISSUE TITLE
allow connection to local DB through Unix socket

### ISSUE THREAD

**Issue by derikson** [heroku/heroku-pg#85]
I don't see that there is currently any way to connect to a database through a Unix socket with `heroku pg:pull`.

The PostgreSQL command line tools connect using a socket if the host part is empty or starts with a slash. But this command changes the host to `localhost` if it's empty, and the host portion of a URI can only contain a slash if it's percent-encoded, but `url.parse()` treats that as part of the path name.

See https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING for reference.

**Comment by msakrejda** [comment]
I believe this was fixed by #97; please let me know if you are still having problems.
