### ISSUE TITLE
heroku pg:psql -c 'select pg_sleep(100)' will fail in the middle due to 20s timeout

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg#94]
https://github.com/heroku/heroku-pg/blob/master/lib/psql.js#L19

Also, seems like you can't really change this timeout, and I'm not really sure where 20s is coming from. Well, maybe for bastion? but still...

**Comment by keiko713** [comment]
```
$ heroku pg:psql -c 'select pg_sleep(100)' -a keiko-sushi
--> Connecting to postgresql-symmetrical-58367
 ▸    psql call timed out
```

**Comment by msakrejda** [comment]
I've looked at this and there's no way to tell when the spawned process has connected to the database and started running the query in the general case. It looks like the timeout was put in during the bastion work in 680a27fcd02f6c0e9e8e4a9b35deb66b16a8dc18 by @idan (and @camilleldn working with him if memory serves?). I think our options are either to let the user override the timeout (ugh --do-the-correct-thing-not-the-wrong-thing flags), drop the timeout entirely (is this reasonable? do you recall why it was put in in the first place @idan @camilleldn?), or live with it. Thoughts?

**Comment by idan** [comment]
I don't recall, rereading and trying to remember.

**Comment by idan** [comment]
Ahh, I think I remember why this is.

So, the actual work is accomplished by the `spawn()` call, which is asynchronous. I think that without the timeout, execution for the scope completes and everything therein is tossed, including the in-progress psql call.

@camilleldn @uhoh-itsmaciek prrreettty sure that's the reason. I remember wrestling with "why doesn't the psql command seem to get executed?"

**Comment by idan** [comment]
I think that means that we must have the timeout in place, or some other synthetic means to keep node from terminating before the PSQL call returns. We tried to use spawnSync but it didn't work because `$FORGOTTEN_REASONS`.

**Comment by msakrejda** [comment]
`spawnSync` doesn't work because of bastions--with a bastion, psql is initially connecting to the proxy process that the CLI itself is running, so it can't spawn psql synchronously because it needs to handle its incoming connection as soon as it spawns it.

**Comment by msakrejda** [comment]
@idan @camilleldn so, tried removing the timeout and still works in both private and non-private databases. The only downside I can think of is uglier behavior (essentially the command would get stuck until you Ctrl+C) *if* the database is unreachable (e.g., bad bastion or service incident). I think it's worth it to fix this. Thoughts?

**Comment by idan** [comment]
+1
